# services:
#   app:
#     image: wepieces_v1:latest
#     env_file:
#       - .env
#     environment:
#       - PORT=${PORT}
#     deploy:
#       mode: replicated
#       replicas: 3
#     networks:
#       - webnet

#   nginx:
#     image: nginx:latest
#     ports:
#       - "3000:80" # Expose only NGINX on port 3000
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - app
#     networks:
#       - webnet

# networks:
#   webnet:

services:
  app:
    image: wepieces_v1:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
